version: "3.8"

services:

  gateway:
    image: nginx:1.19.8-alpine
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ./Gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./Gateway/api_gateway.conf:/etc/nginx/api_gateway.conf

  auth-service:
    image: auth-service:compose_build
    restart: on-failure
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${AUTH_SERVICE_PORT}
      MONGODB_URI: mongo-db:27017
    depends_on:
      - mongo-db

  follow-service:
    image: follow-service:compose_build
    restart: on-failure
    build:
      context: ./follow-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${FOLLOW_SERVICE_PORT}
      USER_SERVICE_DOMAIN: ${USER_SERVICE_DOMAIN}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      MONGODB_URI: mongo-db:27017
    depends_on:
      - mongo-db

  user-service:
    image: user-service:compose_build
    restart: on-failure
    build:
      context: ./user-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${USER_SERVICE_PORT}
      AUTH_SERVICE_DOMAIN: ${AUTH_SERVICE_DOMAIN}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      POST_SERVICE_DOMAIN: ${POST_SERVICE_DOMAIN}
      POST_SERVICE_PORT: ${POST_SERVICE_PORT}
      FOLLOW_SERVICE_DOMAIN: ${FOLLOW_SERVICE_DOMAIN}
      FOLLOW_SERVICE_PORT: ${FOLLOW_SERVICE_PORT}
      MONGODB_URI: mongo-db:27017
    depends_on:
      - mongo-db


  post-service:
    image: post_service:compose_build
    restart: on-failure
    build:
      context: ./post-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${FOLLOW_SERVICE_PORT}
      USER_SERVICE_DOMAIN: ${USER_SERVICE_DOMAIN}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      FOLLOW_SERVICE_DOMAIN: ${FOLLOW_SERVICE_DOMAIN}
      FOLLOW_SERVICE_PORT: ${FOLLOW_SERVICE_PORT}
      MONGODB_URI: mongo-db:27017
    depends_on:
      - mongo-db


  mongo-db:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db
    networks:
      - backend




networks:
  backend:
    name: back
    driver: bridge